server:
  port: 7002

spring.data.mongodb:
  host: localhost
  port: 27017
  database: recommendation-db

logging:
  level:
    root: info
    com.salapp: debug
    org.springframework.data.mongodb.core.MongoTemplate: debug

---
spring:
  profiles: docker
  data:
    mongodb:
      host: mongodb
server:
  port: 8080
